name: 'Cloudflare DNS LetsEncrypt Certificate Generator'
description: 'Generating LetsEncrypt certificate with DNS challenge for domains parked in Cloudflare'
author: 'Shibly Meeran'
inputs:
  cloudflare_api_token:
    description: 'Cloudflare API token with Zone:DNS:Edit permission'
    required: true
  domain_names:
    description: 'The fully qualified domain names for which certificate is required (comma separated)'
    required: true
  email:
    description: 'Email address (to notify on certificate expiry)'
    required: true
  cert_file_name:
    description: 'The name of the file to which the generated keys and certificates will be stored in zip format [default: cert]'
    required: false
    default: 'cert'
  dry_run:
    description: '[true/false] Will only simulate the process using DNS challenge. Will not issue an actual certificate'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cloudflare_api_token }}
    - ${{ inputs.domain_names }}
    - ${{ inputs.email }}
    - ${{ inputs.cert_file_name }}
    - ${{ inputs.dry_run }}